import type {
  Property,
  TenantApp,
  Payment,
  MaintenanceTicket,
  Artisan,
  LordApp,
  LordLease,
  LordTicket,
} from "./types"

export const PROPERTIES: Property[] = [
  {
    id: "p1",
    title: "Sunlit 2BR Apartment",
    type: "Apartment",
    area: "East Legon",
    region: "Greater Accra",
    beds: 2,
    baths: 2,
    sqft: 1100,
    priceLabel: "₵2,500",
    priceShort: "₵2.5k",
    advance: "3 months",
    escrowLabel: "₵7,500",
    escrowTotal: "₵5,025",
    serviceFee: "₵25",
    desc: "A bright, well-ventilated apartment on the 3rd floor with stunning views of East Legon hills. The unit features a modern open-plan kitchen, fitted wardrobes, and a private balcony. Located 5 minutes from the Accra Mall.",
    amenities: [
      "Air conditioning",
      "Fitted kitchen",
      "24/7 security",
      "Covered parking",
      "Backup generator",
      "Water storage",
    ],
    landlord: {
      name: "Ama Owusu",
      initials: "AO",
      since: "2019",
      rating: "4.8",
    },
    pinX: 58,
    pinY: 34,
  },
  {
    id: "p2",
    title: "Modern Studio in Cantonments",
    type: "Studio",
    area: "Cantonments",
    region: "Greater Accra",
    beds: 1,
    baths: 1,
    sqft: 620,
    priceLabel: "₵1,800",
    priceShort: "₵1.8k",
    advance: "2 months",
    escrowLabel: "₵3,600",
    escrowTotal: "₵3,618",
    serviceFee: "₵18",
    desc: "Compact but stylish studio in the diplomatic enclave. Walking distance to embassies and international schools. Recently renovated with premium finishes.",
    amenities: [
      "Fully furnished",
      "Fast internet",
      "Swimming pool",
      "Gym access",
      "Concierge",
      "DSTV",
    ],
    landlord: {
      name: "Kwesi Mensah",
      initials: "KM",
      since: "2021",
      rating: "4.6",
    },
    pinX: 38,
    pinY: 52,
  },
  {
    id: "p3",
    title: "Spacious 3BR Family Home",
    type: "House",
    area: "Osu",
    region: "Greater Accra",
    beds: 3,
    baths: 2,
    sqft: 1850,
    priceLabel: "₵3,800",
    priceShort: "₵3.8k",
    advance: "6 months",
    escrowLabel: "₵22,800",
    escrowTotal: "₵7,638",
    serviceFee: "₵38",
    desc: "Detached family home with a lush garden in one of Accra's most vibrant neighbourhoods. Large compound with children's play area and domestic staff quarters.",
    amenities: [
      "Garden",
      "Domestic quarters",
      "Borehole water",
      "Solar power",
      "CCTV",
      "Electric gate",
    ],
    landlord: {
      name: "Abena Asante",
      initials: "AA",
      since: "2017",
      rating: "4.9",
    },
    pinX: 22,
    pinY: 44,
  },
  {
    id: "p4",
    title: "Executive 1BR in Labone",
    type: "Apartment",
    area: "Labone",
    region: "Greater Accra",
    beds: 1,
    baths: 1,
    sqft: 780,
    priceLabel: "₵2,100",
    priceShort: "₵2.1k",
    advance: "3 months",
    escrowLabel: "₵6,300",
    escrowTotal: "₵4,221",
    serviceFee: "₵21",
    desc: "Premium one-bedroom in the heart of Labone close to Oxford Street. Fully tiled, with modern appliances and a spacious balcony.",
    amenities: [
      "Air conditioning",
      "Fitted kitchen",
      "Elevator",
      "Security",
      "Parking",
      "Water",
    ],
    landlord: {
      name: "Kofi Agyeman",
      initials: "KA",
      since: "2020",
      rating: "4.7",
    },
    pinX: 70,
    pinY: 62,
  },
]

export const WALK_ROOMS = [
  "Living room",
  "Master bedroom",
  "Kitchen",
  "Bathroom",
  "Balcony",
]

export const TENANT_APPS: TenantApp[] = [
  {
    id: "a1",
    propertyId: "p1",
    property: "Sunlit 2BR Apartment",
    area: "East Legon",
    price: "₵2,500/mo",
    landlord: "Ama Owusu",
    bg: "Both checks passed",
    date: "Applied 20 Jun 2026",
    status: "Active lease",
    statusColor: "#10B981",
  },
  {
    id: "a2",
    propertyId: "p4",
    property: "Executive 1BR in Labone",
    area: "Labone",
    price: "₵2,100/mo",
    landlord: "Kofi Agyeman",
    bg: "Checks in progress",
    date: "Applied 18 Jun 2026",
    status: "Under review",
    statusColor: "#D97706",
  },
  {
    id: "a3",
    propertyId: "p2",
    property: "Modern Studio in Cantonments",
    area: "Cantonments",
    price: "₵1,800/mo",
    landlord: "Kwesi Mensah",
    bg: "Checks passed",
    date: "Applied 14 Jun 2026",
    status: "Awaiting sign",
    statusColor: "#047857",
  },
]

export const PAYMENTS: Payment[] = [
  {
    id: "pay1",
    label: "June 2026 rent",
    date: "01 Jun 2026",
    method: "MTN MoMo",
    amount: "₵2,500",
    status: "Paid",
    color: "#10B981",
  },
  {
    id: "pay2",
    label: "May 2026 rent",
    date: "01 May 2026",
    method: "MTN MoMo",
    amount: "₵2,500",
    status: "Paid",
    color: "#10B981",
  },
  {
    id: "pay3",
    label: "April 2026 rent",
    date: "01 Apr 2026",
    method: "Bank transfer",
    amount: "₵2,500",
    status: "Paid",
    color: "#10B981",
  },
  {
    id: "pay4",
    label: "March 2026 rent",
    date: "01 Mar 2026",
    method: "MTN MoMo",
    amount: "₵2,500",
    status: "Paid",
    color: "#10B981",
  },
  {
    id: "pay5",
    label: "Security deposit",
    date: "01 Aug 2026",
    method: "Escrow",
    amount: "₵2,500",
    status: "In escrow",
    color: "#047857",
  },
]

export const MAINTENANCE_TICKETS: MaintenanceTicket[] = [
  {
    id: "m1",
    title: "Leaking kitchen tap",
    category: "Plumbing",
    date: "20 Jun 2026",
    artisan: "Kofi Plumbing Co.",
    status: "In progress",
    color: "#D97706",
  },
  {
    id: "m2",
    title: "AC unit not cooling",
    category: "HVAC",
    date: "15 Jun 2026",
    artisan: "CoolAir Ghana",
    status: "Scheduled",
    color: "#047857",
  },
  {
    id: "m3",
    title: "Broken bedroom light switch",
    category: "Electrical",
    date: "10 Jun 2026",
    artisan: "Volta Electricals",
    status: "Completed",
    color: "#10B981",
  },
  {
    id: "m4",
    title: "Repaint living room walls",
    category: "Painting",
    date: "05 Jun 2026",
    artisan: "Unassigned",
    status: "Open",
    color: "#6B7280",
  },
]

export const ARTISANS: Artisan[] = [
  {
    id: "ar1",
    name: "Kofi Plumbing Co.",
    initials: "KP",
    trade: "Plumbing",
    rating: "4.9",
    jobs: "142 jobs",
    area: "East Legon & Osu",
    rate: "₵80 callout",
  },
  {
    id: "ar2",
    name: "Volta Electricals",
    initials: "VE",
    trade: "Electrical",
    rating: "4.8",
    jobs: "98 jobs",
    area: "Greater Accra",
    rate: "₵90 callout",
  },
  {
    id: "ar3",
    name: "BrightCoat Painters",
    initials: "BC",
    trade: "Painting",
    rating: "4.7",
    jobs: "67 jobs",
    area: "Accra & Tema",
    rate: "₵120 / day",
  },
  {
    id: "ar4",
    name: "CoolAir Ghana",
    initials: "CA",
    trade: "HVAC",
    rating: "4.9",
    jobs: "211 jobs",
    area: "All Accra",
    rate: "₵150 callout",
  },
  {
    id: "ar5",
    name: "Akua Beauty Studio",
    initials: "AB",
    trade: "Hair & beauty",
    rating: "4.8",
    jobs: "320 jobs",
    area: "East Legon",
    rate: "₵60 / visit",
  },
  {
    id: "ar6",
    name: "FixRight Carpentry",
    initials: "FR",
    trade: "Carpentry",
    rating: "4.6",
    jobs: "54 jobs",
    area: "Cantonments & Labone",
    rate: "₵100 / day",
  },
]

export const LORD_APPS: LordApp[] = [
  {
    id: "la1",
    tenant: "Ama Darko",
    initials: "AD",
    property: "Sunlit 2BR · East Legon",
    date: "20 Jun 2026",
    income: "₵9,500 / mo",
    bgStatus: "Passed",
    bgColor: "#10B981",
  },
  {
    id: "la2",
    tenant: "Kwame Asante",
    initials: "KA",
    property: "Studio · Cantonments",
    date: "19 Jun 2026",
    income: "₵6,200 / mo",
    bgStatus: "In progress",
    bgColor: "#D97706",
  },
  {
    id: "la3",
    tenant: "Efua Boateng",
    initials: "EB",
    property: "3BR Home · Osu",
    date: "16 Jun 2026",
    income: "₵14,000 / mo",
    bgStatus: "Passed",
    bgColor: "#10B981",
  },
]

export const LORD_LEASES: LordLease[] = [
  {
    id: "ll1",
    propertyId: "p1",
    tenant: "Ama Darko",
    initials: "AD",
    property: "Sunlit 2BR · East Legon",
    rent: "₵2,500",
    rentPesewas: 250000,
    start: "01 Aug 2026",
    end: "31 Jul 2027",
    nextDue: "01 Jul 2026",
    status: "Active",
    statusColor: "#10B981",
  },
  {
    id: "ll2",
    propertyId: "p2",
    tenant: "Kojo Mensah",
    initials: "KM",
    property: "Studio · Cantonments",
    rent: "₵1,800",
    rentPesewas: 180000,
    start: "01 Mar 2026",
    end: "28 Feb 2027",
    nextDue: "01 Jul 2026",
    status: "Active",
    statusColor: "#10B981",
  },
  {
    id: "ll3",
    propertyId: "p3",
    tenant: "Abena Opoku",
    initials: "AO",
    property: "3BR Home · Osu",
    rent: "₵3,800",
    rentPesewas: 380000,
    start: "01 Jan 2026",
    end: "31 Dec 2026",
    nextDue: "01 Jul 2026",
    status: "Active",
    statusColor: "#10B981",
  },
  {
    id: "ll4",
    propertyId: "p4",
    tenant: "Fiifi Quaye",
    initials: "FQ",
    property: "Executive 1BR · Labone",
    rent: "₵2,100",
    rentPesewas: 210000,
    start: "01 Nov 2025",
    end: "31 Oct 2026",
    nextDue: "—",
    status: "Expiring soon",
    statusColor: "#D97706",
  },
]

export const LORD_TICKETS: LordTicket[] = [
  {
    id: "lt1",
    property: "Sunlit 2BR · East Legon",
    tenant: "Ama Darko",
    issue: "Leaking kitchen tap",
    category: "Plumbing",
    date: "20 Jun 2026",
    artisan: "Kofi Plumbing Co.",
    status: "In progress",
    statusColor: "#D97706",
  },
  {
    id: "lt2",
    property: "Studio · Cantonments",
    tenant: "Kojo Mensah",
    issue: "AC unit not cooling",
    category: "HVAC",
    date: "18 Jun 2026",
    artisan: "CoolAir Ghana",
    status: "Scheduled",
    statusColor: "#047857",
  },
  {
    id: "lt3",
    property: "3BR Home · Osu",
    tenant: "Abena Opoku",
    issue: "Gate motor faulty",
    category: "Electrical",
    date: "15 Jun 2026",
    artisan: "Volta Electricals",
    status: "Completed",
    statusColor: "#10B981",
  },
  {
    id: "lt4",
    property: "Executive 1BR · Labone",
    tenant: "Fiifi Quaye",
    issue: "Ceiling fan wobbling",
    category: "Electrical",
    date: "12 Jun 2026",
    artisan: "Unassigned",
    status: "Open",
    statusColor: "#6B7280",
  },
]
